[project]
name = "gluework-tracker"
version = "0.1.0"
description = "GitHub bot is for analyzing Glue Work contributions contributors have made in OSS projects."
readme = "README.md"
requires-python = ">=3.10,<4.0"
dependencies = []
