name: Main
on:
  push:
    branches:
      - main
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"
  pull_request:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      sha:
        description: "the git sha to checkout and build"
        required: true
        type: string
permissions:
  contents: read
  actions: read
  id-token: write
  pages: write
  security-events: write
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  checks:
    uses: ./.github/workflows/checks.yaml
    secrets: inherit
    with:
      sha: ${{ inputs.sha || github.sha }}
  build-wheels:
    uses: ./.github/workflows/build-wheels.yaml
    secrets: inherit
    with:
      sha: ${{ inputs.sha || github.sha }}
  build-docs:
    uses: ./.github/workflows/build-docs.yaml
    secrets: inherit
    with:
      sha: ${{ inputs.sha || github.sha }}
  codeql:
    uses: ./.github/workflows/codeql.yaml
    secrets: inherit
    with:
      sha: ${{ inputs.sha || github.sha }}
  release:
    uses: ./.github/workflows/release.yaml
    secrets: inherit
    needs:
      - build-docs
      - build-wheels
      - checks
      - codeql
    with:
      sha: ${{ inputs.sha || github.sha }}
      publish-docs: ${{ github.ref_name == 'main' }}
